server:
  port: 8080

spring:
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: qwen2.5:3b
      embedding:
        options:
          model: nomic-embed-text

dart:
  api:
    base-url: https://opendart.fss.or.kr/api
    key: ${DART_API_KEY:}

company-report:
  index-file: data/company-report-index.json
  vector-store-file: data/company-report-vectorstore.json
